import collections/iterate
export iterate.all
export iterate.dropWhile
export iterate.filter
export iterate.flatMap
export iterate.flatten
export iterate.grouping
export iterate.items
export iterate.map
export iterate.next
export iterate.range
export iterate.reversed
export iterate.someTrue
export iterate.sorted
export iterate.takeWhile
export iterate.unzip
export iterate.zip
